language: python
python:
  - "2.6"
  - "2.7"

# Install dependencies
before_install:
 - sudo apt-get update
 - sudo apt-get install poppler-utils

# Install Python dependencies
install:
  - pip install . --use-mirrors
  - pip install nose --use-mirrors

# Run tests
script: nosetests tests
